import { printSchema } from 'graphql';
import { writeFileSync } from 'fs';

import { schema } from '../src/graphql/schema';

const sdlString = printSchema(schema);
const generatedBy = `# This file was automatically generated by tools/dump-schema.ts\n# Do not edit manually.\n\n`;
writeFileSync('./schema.graphql', generatedBy + sdlString, 'utf8');

console.log('Schema dumped to schema.graphql');
